### ISSUE TITLE
Mangler mellemrum under Rettighedsnoter i AarhusArkivet

### ISSUE THREAD

**Issue by christianbrinkaar** [aarhusstadsarkiv/aarhusarkivet#33]
Der mangler et mellemrum før denne tekst: _Materialet er online her på Aarhusarkivet.dk, men må jf. ”Museumsaftalen” med Copydan ikke gengives andre steder._

Det gælder alle registreringer med tekst om Museumsaftalen.

https://www.aarhusarkivet.dk/records/000315466

**Comment by clausjuhl** [comment]
Jeg har ændret det til en "bug" :) Det skal rettes manuelt ved at hente registreringerne ind i SAM igen. Det er @JanneMarieBarslev , der har skrevet og uploaded teksten, så jeg sender giver hende besked, og beder hende samtidig kommentere på dette issue, når hun har rettet fejlen.

**Comment by JanneMarieBarslev** [comment]
Jeg er opmærksom på fejlen, men jeg kan ikke gennemskue en nem måde at rette det på.
Teksten er først lavet ved at tilføje teksten om museumsaftalen til en allerede eksisterende tekst ved at trække det ind i refine. Jeg fik i sin tid ikke sat et mellemrum ind først, og nu ved jeg ikke hvordan man kodemæssigt tilføjer et mellemrum i refine midt i en tekst. Alternativt skal man hive samtlige ind i SAM og rettet dem enkeltvis.

**Comment by clausjuhl** [comment]
I Refine kan du skrive følgende i boksen, der åbner sig, når man klikker på "Transform" (mener jeg det hedder) udfor den relevante kolonne:
````
value.replace(".Materialet er online", ". Materialet er online")
````
Denne funktion erstatter den første tekststreng med den anden. Giver det mening?

**Comment by JanneMarieBarslev** [comment]
Thank you.
Nu når vi er ved det, hvad er koden til et linjeskift. Det vil jeg egentligt hellere have end et mellemrum.

Fra: Claus Juhl Knudsen ***@***.***>
Sendt: 26. maj 2021 09:57
Til: aarhusstadsarkiv/aarhusarkivet ***@***.***>
Cc: Janne Marie Barslev ***@***.***>; Mention ***@***.***>
Emne: Re: [aarhusstadsarkiv/aarhusarkivet] Mangler mellemrum under Rettighedsnoter i AarhusArkivet (#33)


I Refine kan du skrive følgende i boksen, der åbner sig, når man klikker på "Transform" (mener jeg det hedder) udfor den relevante kolonne:

value.replace(".Materialet er online", ". Materialet er online")



Denne funktion erstatter den første tekststreng med den anden. Giver det mening?

-

**Comment by clausjuhl** [comment]
Prøv at skrive "\n" i stedet for mellemrummet.

**Comment by JanneMarieBarslev** [comment]
Thank you very much, Sir.
Det er fikset nu.

Fra: Claus Juhl Knudsen ***@***.***>
Sendt: 26. maj 2021 10:28
Til: aarhusstadsarkiv/aarhusarkivet ***@***.***>
Cc: Janne Marie Barslev ***@***.***>; Mention ***@***.***>
Emne: Re: [aarhusstadsarkiv/aarhusarkivet] Mangler mellemrum under Rettighedsnoter i AarhusArkivet (#33)


Prøv at skrive "\n" i stedet for mellemrummet.

-

**Comment by clausjuhl** [comment]
Janne Marie har fikset problemet.
