### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by christianbrinkaar** [aarhusstadsarkiv/aarhusarkivet#37]
**Beskriv fejlen**

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Hvordan kan man se fejlen?**

1. Lav en søgning i AarhusArkivet på en entitet f.eks. "Busgaden"
2. Gå tilbage til forsiden
3. Lav den samme søgning "Busgaden" som fritekst

**Computer:**
Windows

**Comment by christianbrinkaar** [comment]
Fejlen opstår i Firefox ... 👎

**Comment by clausjuhl** [comment]
Der er tale om en edgecase, som kræver en del ressourcer at fikse. Jeg tillader mig at ignorer den indtil videre. Hvis problemet også begynder at opstå i andre browsere, indberetter vi det som bug igen.
