### ISSUE TITLE
Forkerte previews på video

### ISSUE THREAD

**Issue by christianbrinkaar** [aarhusstadsarkiv/aarhusarkivet#39]
**Beskriv fejlen**
Forkerte previews på nogle film i AarhusArkivet. 

**Hvordan kan man se fejlen?**
https://www.aarhusarkivet.dk/search?direction=desc&sort=created_at&content_types=87&start=60

**Skærmbilleder**
Tilføj gerne skærmbilleder, hvis det hjælper med at forklare fejlen.
![Udklip](https://user-images.githubusercontent.com/84772927/134484575-af472eb3-1a01-4413-a99f-84328d320c02.PNG)

**Computer:**
 - OS: [Windows]
 - Browser [eks. Firefox og Edge]

Dette er blot en orientering. Så du behøver ikke at forklare :-)

Mvh Christian

**Comment by clausjuhl** [comment]
Tak for det! Det lader til at være et problem hos Vimeo, hvorfra thumbsnails vises. Vi ser lige tiden an. Forventer at de fikser det hurtigt.

**Comment by clausjuhl** [comment]
Vi er flyttet fra Vimeo, så problemet er løst.
