### ISSUE TITLE
Kan ikke lave søgning før år 1500.

### ISSUE THREAD

**Issue by JanneMarieBarslev** [aarhusstadsarkiv/aarhusarkivet#40]
Man kan ikke lave en datosortering, der går før 1500, hvilket er problematisk da vi har materiale, der er ældre end dette (se vedhæftede).
Jeg vil eksempelvis gerne lave en søgning, der går fra 1450-1858, da jeg skal have rettet nogle kort, der blot er registeret som billeder og ikke kort.

![Clipboard04](https://user-images.githubusercontent.com/82880158/135814753-2b24594e-de49-4293-8678-8624976a6f93.jpg)

**Comment by clausjuhl** [comment]
Så skulle det gerne være muligt at sortere efter dato fra og med år 1200. Det er muligvis nødvendigt at trykke F5 på hjemmesiden før ændringer slår igennem.

**Comment by JanneMarieBarslev** [comment]
Thanks :-)
