### ISSUE TITLE
Søgning med *

### ISSUE THREAD

**Issue by JanneMarieBarslev** [aarhusstadsarkiv/aarhusarkivet#45]
Når man søger på resultaterne sporvognsremisen og sporvognsremise" får man to helt forskellige resultater.

sporvognsremisen giver 27 hits (https://www.aarhusarkivet.dk/search?q=sporvognsremisen).

sporvognsremise* burde potentielt set fange flere (så vidt jeg kan regne ud), men den giver 0 hits (https://www.aarhusarkivet.dk/search?q=sporvognsremise*)

**Comment by clausjuhl** [comment]
Det er desværre en "bug" ved den søgemaskine vi bruger hos Amazon. Jeg vil ikke engang forsøge at forklare hvorfor, men her er Amazons forklaring:

> For example, if you search the actor field in the sample movie data for Anders, there are three matching movies. If you search for Ander*, you get those movies as well as several others. However, if you search for Anders* there are no matches. This is because the term is stored in the index as ander, anders does not appear in the index. For more information about how Amazon CloudSearch processes text and how it can affect searches, see [Text Processing in Amazon CloudSearch](https://docs.aws.amazon.com/cloudsearch/latest/developerguide/text-processing.html).

Hvis du søger efter "sporvognsremis*" får du igen 28 resultater. Vi kan ikke gøre noget ved det, før den dag, hvor vi skifter søgemaskine.

**Comment by JanneMarieBarslev** [comment]
Jamen, så er det jo sådan det er 😊

Fra: Claus Juhl Knudsen ***@***.***>
Sendt: 1. april 2022 09:55
Til: aarhusstadsarkiv/aarhusarkivet ***@***.***>
Cc: Janne Marie Barslev ***@***.***>; Author ***@***.***>
Emne: Re: [aarhusstadsarkiv/aarhusarkivet] Søgning med * (Issue #45)


Det er desværre en "bug" ved den søgemaskine vi bruger hos Amazon. Jeg vil ikke engang forsøge at forklare hvorfor, men her er Amazons forklaring:

For example, if you search the actor field in the sample movie data for Anders, there are three matching movies. If you search for Ander*, you get those movies as well as several others. However, if you search for Anders* there are no matches. This is because the term is stored in the index as ander, anders does not appear in the index. For more information about how Amazon CloudSearch processes text and how it can affect searches, see Text Processing in Amazon CloudSearch<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2Fcloudsearch%2Flatest%2Fdeveloperguide%2Ftext-processing.html&data=04%7C01%7Cjabar%40aarhus.dk%7C8fde698fd0a14530cd0f08da13b4f865%7C7d66e3797f9441f8a2bafc9740f2faa0%7C1%7C0%7C637843965225744047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9aVeEx%2FiJMJaHiGbqOlFlmoIqDCoxRFJ9CI9ak4VbPc%3D&reserved=0>.

Hvis du søger efter "sporvognsremis*" får du igen 28 resultater. Vi kan ikke gøre noget ved det, før den dag, hvor vi skifter søgemaskine.
